config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/tab', to: 'tab#index', as: 'tab'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_user.rb
class GithubUser
  attr_reader :login,
              :avatar_url,
              :name,
              :bio,
              :company,
              :location,
              :blog,
              :email,
              :followers,
              :following,
              :public_repos

  def initialize(attrs)
    @attrs = attrs
    @login = attrs[:login]
    @avatar_url = attrs[:avatar_url]
    @name = attrs[:name]
    @bio = attrs[:bio]
    @company = attrs[:company]
    @location = attrs[:location]
    @blog = attrs[:blog]
    @email = attrs[:email]
    @followers = attrs[:followers]
    @following = attrs[:following]
    @public_repos = attrs[:public_repos]
  end

  def self.current_user_info(login, token)
    new(GithubService.current_user_info(login, token))
  end

  def self.get_followers(login, token)
    logins = GithubService.get_followers(login, token)

    logins.map do |follower|
      current_user_info(follower, token)
    end
  end

  def self.get_following(login, token)
    logins = GithubService.get_following(login, token)

    logins.map do |following|
      current_user_info(following, token)
    end
  end

  private
    attr_reader :attrs
end

app/models/org.rb
class Org
  attr_reader :login,
              :avatar_url

  def initialize(attrs)
    @attrs = attrs
    @login = attrs[:login]
    @avatar_url = attrs[:avatar_url]
  end

  def self.get_orgs(login, token)
    organizations = GithubService.get_orgs(login, token)

    organizations.map do |org_login|
      current_user_info(org_login, token)
    end
  end

  private
    attr_reader :attrs
end

app/models/repo.rb
class Repo
  attr_reader :name,
              :forked,
              :description,
              :updated_at,
              :parent_full_name,
              :language,
              :forks

  def initialize(attrs)
    @attrs = attrs
    @name = attrs[:name]
    @forked = attrs[:fork]
    @description = attrs[:description]
    @updated_at = attrs[:updated_at]
    @parent_full_name = attrs[:parent][:full_name] if @forked
    @language = attrs[:language]
    @forks = attrs[:parent][:forks_count] if @forked
  end

  def self.get_repos(login, token)
    repos = GithubService.get_repos(login, token)

    repos.map do |repo_path|
      get_repo_data(repo_path, token)
    end
  end

  def self.get_repo_data(login, token)
    new(GithubService.get_repo_data(login, token))
  end

  private
    attr_reader :attrs
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(provider: auth['provider'], uid: auth['uid'])

    user.nickname = auth['info']['nickname']
    user.name = auth['info']['name']
    user.email = auth['info']['email']
    user.image_url = auth['info']['image']
    user.token = auth['credentials']['token']

    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      response = Faraday.get("https://api.github.com/users/marinacor1?access_token=4e4086ae85c7b0e17fe9edae295fc748a2c7576b") ##{current_user.nickname}
      json_response = JSON.parse(response.body, symbolize_names:true)
      @github_user = GithubUser.new(json_response)
      
      followers_response = Faraday.get("https://api.github.com/users/marinacor1/followers?access_token=4e4086ae85c7b0e17fe9edae295fc748a2c7576b")
      @followers = JSON.parse(followers_response.body, symbolize_names:true).map do |follower_info|
        follower_data = Faraday.get(follower_info[:url]+"?access_token=4e4086ae85c7b0e17fe9edae295fc748a2c7576b")
        GithubUser.new(JSON.parse(follower_data.body, symbolize_names:true))
      end

      orgs_response = Faraday.get("https://api.github.com/users/marinacor1/orgs?access_token=4e4086ae85c7b0e17fe9edae295fc748a2c7576b")
      @orgs = JSON.parse(orgs_response.body, symbolize_names:true).map do |org_info|
        org_data = Faraday.get(org_info[:url]+"?access_token=4e4086ae85c7b0e17fe9edae295fc748a2c7576b")
        Org.new(JSON.parse(org_data.body, symbolize_names:true))
      end

    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # binding.pry
    if user = User.find_or_create_from_auth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/tab_controller.rb
class TabController < ApplicationController
  def index
    if current_user
      @github_user = GithubUser.current_user_info(current_user.nickname, current_user.token)

      @orgs = Org.get_orgs(current_user.nickname, current_user.token)

    end

    if params[:category] == 'followers'
      @follows = GithubUser.get_followers(current_user.nickname, current_user.token)
    elsif params[:category] == 'following'
      @follows = GithubUser.get_following(current_user.nickname, current_user.token)
    elsif params[:category] == 'repositories'
      @repos = Repo.get_repos(current_user.nickname, current_user.token)
    else
      #activity feed
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_navbar.html.erb
  <section class='profile_navbar'>
    <a>Overview</a>
    <a>Repositories <span class="counter"><%= @github_user.public_repos %></span></a>
    <a>Followers <span class="counter"><%= @github_user.followers %></span></a>
    <a>Following <span class="counter"><%= @github_user.following %></span></a>
  </section>

app/views/home/index.html.erb
<% if current_user %>
  <span class='grid'>
    <%= render partial: 'tab/navbar' %>
  </span>
<% end %>

app/views/layouts/_navbar.html.erb
<% if current_user %>
  <div class="navbar">
    <%= "Welcome #{current_user.nickname}" %>
    <%= link_to "Sign out", logout_path, class: "nav_links" %>
  </div>
<% else %>
  <div class="navbar">
  <%= link_to "Sign in with Github", github_login_path %>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <% if current_user %>
    <%= image_tag @github_user.avatar_url, class: "avatar" %>
    <div class="card">
      <h1 class="name"><%= @github_user.name %></h1>
      <p class="login"><%= @github_user.login %></p>
    </div>
    <p class="bio"><%= @github_user.bio %></p>
    <div class="card">
      <p class="company"><%= @github_user.company %></p>
      <p class="location"><%= @github_user.location %></p>
      <p class="email"><%= current_user.email %></p>
      <p class="blog"><%= @github_user.blog %></p>
    </div>
    <% if @orgs %>
      <div class="card">
        <h2>Organizations</h2>
        <% @orgs.each do |organization| %>
          <%= image_tag organization.avatar_url, class: "xs_avatar" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>Log in to show data</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApicuriousGithub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
    <%= render partial: "layouts/navbar" %>
  <body>
    <div class='parent'>
      <%= render partial: "layouts/sidebar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tab/_follows.html.erb
   <% @follows.each do |user_follow| %>
      <section class="follow_card">
        <div>
          <%= image_tag user_follow.avatar_url, class: "s_avatar" %>
        </div>
        <div class="follow_data">
          <span class='name_data'>
            <p class='user_follow_name'><%= user_follow.name %></p>
            <p><%= user_follow.login %></p>
          </span>
          <p class='bio'><%= user_follow.bio %></p>
          <span class='contact_data'>
            <p><%= user_follow.location %></p>
            <p><%= user_follow.company %></p>
          </span>
        </div>
      </section>
    <% end %>

app/views/tab/_navbar.html.erb
  <section class='profile_navbar'>

    <a href="/tab?category=overview" class="activity_link">Overview</a>

    <a href="/tab?category=repositories" class="repositories_link">Repositories <span class="counter"><%= @github_user.public_repos %></span></a>

    <a href="/tab?category=followers" class="followers_link">Followers <span class="counter"><%= @github_user.followers %></span></a>

    <a href="/tab?category=following" class="following_link">Following <span class="counter"><%= @github_user.following %></span></a>

  </section>

app/views/tab/_repos.html.erb
    <% @repos.each do |repo| %>
      <h2 class="repo_name"><%= repo.name %></h2>
      <% if repo.forked %>
        <p class="parent_full_name">Forked from <%= repo.parent_full_name %></p>
      <% end %>
      <p class="description"><%= repo.description %></p>
      <div>
        <p class="language"><%= repo.language %></p>
        <p class="forks"><%= repo.forks %></p>
        <p class="updated_at">Updated <%= distance_of_time_in_words(repo.updated_at, Time.now) %> ago</p>
      </div>
    <% end %>

app/views/tab/index.html.erb
<span class='grid'>
  <%= render partial: "navbar" %>

  <% if @repos %>
    <%= render partial: 'repos' %>
  <% elsif @follows %>
    <%= render partial: 'follows' %>
  <% else %>

  <% end %>
</span>